server:
  port: 8082

eureka:
  client:
    serviceUrl.defaultZone: http://discovery-service:8761/eureka

spring:

  application:
    name: mail-service

  # kafka properties
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: group_id
      auto-offset-reset: earliest
      properties:
#        spring.json.trusted.packages: "com.tascigorkem.mailservice.dto.kafka"
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false

  mail:
    host: mailhog
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
    addresses:
      from: gorkem_tasci@hotmail.com
      replyTo: gorkem_tasci@hotmail.com

  thymeleaf:
    check-template-location: true
    prefix: 'classpath:/templates/'
    suffix: .html
    mode: HTML5
    encoding: UTF-8

  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

# kafka topics
my-message-topic:
  name: my-topic
  num-partitions: 1
  replication-factor: 1
  messages-per-request: 10


my-object-topic:
  name: my-object-topic
  num-partitions: 1
  replication-factor: 1
  messages-per-request: 10

# logging
logging:

  # level
  level:
    org.springframework: ERROR
    com.tascigorkem.mailservice: DEBUG

  # output to a file
  file.name: app.log
  pattern.file: '%d %p %c{1.} [%t] %m%n'
  pattern.console: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n'

---

spring:
  profiles: local

  # kafka properties
  kafka:
    bootstrap-servers: 127.0.0.1:9092

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka
